### ISSUE TITLE
Old search, next page functions on certain pages [low priority]

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#102]
**Is your feature request related to a problem? Please describe.**
The Parts, Plates, and Samples pages have what appears to be an older page view compared to the other pages. Certain features are missing, such as the box to change how many records are displayed per page.

**Describe the solution you'd like**
I'd like the Parts, Plates, and Samples pages to have the same UI as the other pages (Collections, Containers, etc).

**Describe alternatives you've considered**
This issue doesn't significantly impact the website. If it's too difficult/time consuming to implement, it can be ignored.

Anything else?
Here's what the older pages look like:
<img width="1205" alt="Screen Shot 2019-10-17 at 11 59 10 AM" src="https://user-images.githubusercontent.com/31907124/67039513-5f0f0c00-f0d6-11e9-86e2-e8413e4b9d00.png">
<img width="1122" alt="Screen Shot 2019-10-17 at 12 04 46 PM" src="https://user-images.githubusercontent.com/31907124/67039538-6a623780-f0d6-11e9-8a10-e1002c3014e0.png">     

And here's what the newer pages look like:
<img width="1174" alt="Screen Shot 2019-10-17 at 12 06 06 PM" src="https://user-images.githubusercontent.com/31907124/67039613-8b2a8d00-f0d6-11e9-8139-59225327bff8.png">
<img width="1141" alt="Screen Shot 2019-10-17 at 12 06 18 PM" src="https://user-images.githubusercontent.com/31907124/67039616-8e257d80-f0d6-11e9-813c-3f9b58f59dfc.png">

**Comment by vsoch** [comment]
It's intentionally like that - the ones with the search have the search because there are way too many records to show on the page, so instead of presenting the user with a single DataTable (with all records, collections, for example) we present them with a paginated view. I added the search box to this view because you cannot rely on the table anymore for a search (as not all records are shown). If you browse around and inspect catalog pages that have many more entities (samples, parts) you'll see the pattern.

The reason you can't choose records per page is because it's not rendered with the same DataTable library, it's custom pagination delivered by the server.

What would be possible to do is try doing a different default for the pagination [right now the function returns 50](https://github.com/vsoch/freegenes/blob/master/fg/apps/main/views/catalog.py#L77).

**Comment by hverdonk** [comment]
Thanks for the insight. Ultimately, I think this one is best left as-is :)
