### ISSUE TITLE
Table Names?

### ISSUE THREAD

**Issue by marc4-stanford** [vsoch/freegenes#134]
On the checkout page, shouldn’t the list of institutions not have the “Institution:” on the select?

![Screen Shot 2019-11-09 at 10 13 24 AM](https://user-images.githubusercontent.com/42281767/68546803-6cdf4680-038f-11ea-8c17-79f380220e16.png)

**Comment by vsoch** [comment]
This is a crispy form, rendered as follows:
```
          <form action="{% url 'upload-mta' order.uuid %}" enctype="multipart/form-data" method="POST">
	    {% csrf_token %}
	    {{ form|crispy }}
	    <button type="submit" class="btn btn-primary">Submit</button>
	  </form>
```
that uses the __str__() method on the Model to render the names. I've standardized it to be represented as `<ModelType: name>` to make it clear, otherwise you wouldn't know it's an institution. This could be changed with a bit of hacking, but is a small detail and likely outside of the scope of current work. I'll add a feature/enhancement label for the future.

**Comment by marc4-stanford** [comment]
Why do the institutions on this page not have the Model name?

![Screen Shot 2019-11-10 at 8 06 01 AM](https://user-images.githubusercontent.com/42281767/68546950-1541da80-0391-11ea-98b1-86be20c362c6.png)

**Comment by vsoch** [comment]
Good question! The part you linked isn't technically a form, it's just a select menu outside of one. 

```html
  <div class="row">
     <div class="col-md-12">
           <div class="list-group">{% for entry in institutions %}
	    <a class="list-group-item list-group-item-action">{{ entry.name }}</a>{% endfor %}
	   </div>
     </div>
  </div>
```
This means that we don't use crispy forms, because there isn't any complex file upload that we need to implement (as there is with the other). And as you see in the above, I can easily loop through a list of institution objects and choose their name to render `{{ entry.name }}`

The form on that page only needs to capture one input value, and it's not linked to a model,  so it's implemented with a manual input field that is validated as POST data (instead of validated with a model form). That looks like this:

```html
  <div class="row">
     <div class="col-md-12">
            <form method="POST" action="{% url 'add_institution' %}">
                {% csrf_token %}
		 <div class="form-group" style='margin-top:10px'>
		    <input type="text" name="institution" class="form-control" id="addInstitution" aria-describedby="addHelp" placeholder="Enter institution name">
		    <small id="addHelp" class="form-text text-muted">Don't see your Institution? Add it here.</small>
		  </div>
                   <button class="btn btn-secondary btn-small" style="float:right" type="submit">Add New Institution</button>
            </form>
     </div>
  </div>
```
