### ISSUE TITLE
Post to api/parts redirected to Get api/parts

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#137]
**Describe the bug**
While trying to test plate importation, I've encountered an error in the part API where posts, when sent to `http://127.0.0.1/api/parts` are converted to gets.

The console gives the following response:
`nginx_1      | 172.17.0.1 - - [11/Nov/2019:19:33:33 +0000] "POST /api/parts HTTP/1.1" 301 0 "-" "python-requests/2.20.1" "-"`
`nginx_1      | 172.17.0.1 - - [11/Nov/2019:19:33:33 +0000] "GET /api/parts/ HTTP/1.1" 200 52 "-" "python-requests/2.20.1" "-"`

**To Reproduce**
- A fresh docker install
-A post to `http://127.0.0.1/api/parts` (NOT the required `http://127.0.0.1/api/parts/`)

**Expected behavior**
A redirect to the post

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
This is actually because the django redirect is ON to handle the trailing slashes, and so your original call gets passed to be a GET. I'm not sure how I'd go about fixing this, but if you have suggestions I'm open! This was one of the rationale for creating freegenes-python to handle this for the user. Personally, I always add trailing slashes.

**Comment by Koeng101** [comment]
I realized it gets passed on, but wasn't really sure if it was something that was easily fixable or not. I'll just close it and use freegenes-python.
