### ISSUE TITLE
Tag Page doesn't work

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#152]
**Describe the bug**
When you visit the tag page, such as https://freegenes.dev/e/tag/73371238-e3ec-4847-93d4-4438ab52ec5f , nothing happens when you press any of the buttons like "Collections" or "Parts".

**To Reproduce**
Visit https://freegenes.dev/e/tag/73371238-e3ec-4847-93d4-4438ab52ec5f

**Expected behavior**
Something happens when you press those buttons, else remove them (completely fine option too)

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
okay all set!

This was an original attempt that I made to allow for dynamic tab content (e.g., not all tags have authors, collections, etc. so we would need to dynamically add the correct classes) but overall it resulted in this bug (nothing working at all!) Instead of trying to do this hack, it's much cleaner to just direct the user to select a tab.
