### ISSUE TITLE
Regenerate Labels When a Shipment Error is Triggered

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#154]
**Is your feature request related to a problem? Please describe.**
If an error occurs in the process of creating a label, the software does not allow me to try creating a different label for the same order. 

Currently, if an error occurs (such as artificially setting both the package and dry ice weights to 2lbs, triggering the Shippo dry ice weight bug), the software will take me to the "generate label" button, then provide me with the error. The shipment itself will have the "track package" button appear, but clicking on it will link back to the same error.

**Describe the solution you'd like**
If an error occurs, the shipment page should not display the "track package" button. Instead, it should show the "create shipment" button and allow me to generate a new label for that order so I can fix my original mistake.

**Describe alternatives you've considered**
I could create a new copy of the order in the Django admin panel, but this is time consuming and may not be associated with the original requester (e.g., they may not be able to actually track their package, as the package is technically associated with a separate, but identical shipment)

Anything else?

**Comment by hverdonk** [comment]
I deliberately triggered the error on the [Dummy Order](https://freegenes.dev/o/details/d69dd1f0-24c5-4fb3-8e25-52a46598ba9e) if you'd like to look at it.

**Comment by vsoch** [comment]
I'm not sure how you got passed this initial check that the shipment weight isn't less than the dry ice:

https://github.com/vsoch/freegenes/blob/master/fg/apps/orders/views/shipping.py#L137

But either way, we should assume that some shipments will be processed that will need to be redone.  There are a few options here:

 - add a button to reset a transaction (meaning removing the label and transaction)
 - given that the user hit an error creating the label, automatically clear the transaction to create again.

I'd suggest the first, because it gives more fine tuned control (and it might be the case that the user doesn't want to reset and redo the order, but wants to see the error from shippo.

**Comment by vsoch** [comment]
All fixed! I clicked the reset shipment button for you, so you'd have to re-generate a bad one again to see it.

**Comment by hverdonk** [comment]
Perfect, thank you! And just as a note, the way I (deliberately) got around the check was to set the dry ice weight and the package weight to be equal, knowing that the dry ice weight in pounds would likely get misinterpreted as kilograms in Shippo's software, making it appear to be larger than the package weight (which would still be read in pounds - ugh, we should've switched to the metric system as a country)

**Comment by hverdonk** [comment]
Button works as expected!
