### ISSUE TITLE
Logging in as superuser created through terminal

### ISSUE THREAD

**Issue by Bovojon** [vsoch/freegenes#185]
Thank you for providing the helpful documentation! 

Once a new superuser is created through the terminal, how can the superuser login on the web app?

**Comment by vsoch** [comment]
The superuser needs to login with an Oauth account first (creating their account on the server) and then adding them via the command line client, [per the instructions here](https://vsoch.github.io/freegenes/docs/development/start#adding-staff-and-superusers). If you create a command line user without logging in first since default django auth is disabled you don't have an easy / straight forward way to login. I recommend taking the approach that I outlined in the docs. You are of course free to change this logic, but at your own risk. Let me know if you have any questions.
