### ISSUE TITLE
Parcel Dimensions (and other questions)?

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#25]
hey @Koeng101 ! Where do the dimensions for a parcel come from? E.g., what populates this schema: https://github.com/Koeng101/flask_freegenes/blob/master/app/models.py#L921

Ideally, we would give the user a default, or a selection from a few defaults.  As a uick refresher, here is what we need to give to the Shippo API:

```python
parcel = {
    "length": "5",
    "width": "5",
    "height": "5",
    "distance_unit": "in",
    "weight": "2",
    "mass_unit": "lb"
}
```

**Comment by vsoch** [comment]
For now (testing) I'll just put in the above for the default, and update when you have some time to discuss!

**Comment by vsoch** [comment]
Another question! So I've successfully created a shipment - and what it includes is the address, the parcel, and a list of rates. What (instinctively) I want to do is to show the rates to the user, and have them choose one. But can you point me to where in your code you do the final "choose this rate" call to the API? And does it give you the actual labels then?

**Comment by Koeng101** [comment]
The dimensions of the parcel pretty much come from me measuring the box we're shipping out.

The "/shipment/rates/{uuid}" is where you can grab the rates for a certain shipment. We choose right now for shipment rates since we are shipping out materials for free. To say "I want this rate", you post to "/shipment/create_label/{uuid}", which generates a label for you.

It'll give you a link to a webpage with the label picture. I usually just print directly from there on our computer.

**Comment by vsoch** [comment]
Okay, in that case the dimensions will be fields in the form, required for creating the shipment. Then I'll return the shipping response to the user with the different rates, have them select, and then (based on your description) I need to use whatever their "Create Label" endpoint is to make the final thing. Thanks!
