### ISSUE TITLE
Questions about contributing

### ISSUE THREAD

**Issue by shea256** [vsoch/freegenes#51]
Hi @vsoch! Very nice to meet you.

As you know, I've been chatting with @Koeng101 about contributing to this codebase. He mentioned you'd love some additional help and so I wanted to reach out on here to discuss the best way for me to get started.

Here's a little bit about me: https://shea.io/about-me.

I've read through your codebase and the contributing guidelines and wrote up some personal notes for myself on navigating the code, so I think I have a good general idea of how it works, but of course I welcome additional information you can share ahead of time.

As far as ways for me to contribute, I have a few ideas but I also want to hear yours. So please let me know what would be the most helpful to you.

Here are some things I worked on as part of a separate similar project and so could incorporate relatively quickly:

1. Improved collection views w/ full lists of parts and other collection attributes
1. Improved part views complete w/ DNA sequences and links back to collections and authors
1. Improved author views w/ full lists of parts
1. A first draft for a writeup for the About page
1. UI testing with pyppeteer / puppeteer
1. Continuous integration with CircleCI

Additionally, going through some of the issues you already have open, I could help out with the following:

1. An improvement to the dashboard layout - #3
1. Improvements to the map view - #43 

Let me know what you think and what is most important / valuable to you.

And once again, really great to meet you and look forward to working together.

Best,
Ryan

**Comment by vsoch** [comment]
hey @shea256 thanks for the detailed intro, and nice to meet you! At this point, since we are early in development I think cleaning up / adding detail to any rough view wouldn't be the best use of time - the entire thing could get changed or refactored and then we would have quite a bit of work. Anything that changes a model at this point, given that we need to be conservative about not changing models / the database, is probably out of the question. But what peaks my interest is something I'm not experienced in (that I'd love to pick up from your work) and that is testing of the UI. I'm familiar with testing on Circle so that would be a benefit too, and actually just writing up general test suites for most of what we have so far would be a huge contribution!

As for the current issues, definitely go forward with #3, and please post screen shots of what you are doing as you go for feedback from everyone, and same with #43. What technologies are you thinking of user, that would work with Django templating?

So to rank order these things, I'd say:

 - #3 
 - #43 
 - UI testing
 - CircleCI testing 

As Keoni probably mentioned to you, you should never push to master branch - all contributions should be done via pull request with discussion first, and maintaining code / license headers for the project. And I'd like you and Keoni to run by helping out with the admin and leader of his group, Marc and Drew, so it's absolutely certain that this is A-OK. I certainly will appreciate the help, and love learning new stuffs! :)

**Comment by shea256** [comment]
> hey @shea256 thanks for the detailed intro, and nice to meet you!

Yes great to meet!

> At this point, since we are early in development I think cleaning up / adding detail to any rough view wouldn't be the best use of time - the entire thing could get changed or refactored and then we would have quite a bit of work.

Sounds good to me.

> But what peaks my interest is something I'm not experienced in (that I'd love to pick up from your work) and that is testing of the UI. I'm familiar with testing on Circle so that would be a benefit too, and actually just writing up general test suites for most of what we have so far would be a huge contribution!

OK I should be able to whip up something simple pretty quick. Let me take a look.

> As for the current issues, definitely go forward with #3, and please post screen shots of what you are doing as you go for feedback from everyone, and same with #43. 

Sounds good on this front as well.

> What technologies are you thinking of user, that would work with Django templating?

I'm not sure yet at this point. There's a good chance I would just work with raw Django templates. I will look through existing dashboard frameworks and see if there's something I can use though.

> As Keoni probably mentioned to you, you should never push to master branch - all contributions should be done via pull request with discussion first, and maintaining code / license headers for the project.

Yes of course. Good coding practices in general :) I'm a fan of protecting the master branch. I like how GitHub lets you block direct commits and even block merges without passing continuous integration reports.

> And I'd like you and Keoni to run by helping out with the admin and leader of his group, Marc and Drew, so it's absolutely certain that this is A-OK.

Sounds good. I'll leave that in @Koeng101's court.

> I certainly will appreciate the help, and love learning new stuffs! :)

And excellent, me too!

**Comment by shea256** [comment]
OK heard from @Koeng101 that we've got the go-ahead.

**Comment by vsoch** [comment]
Going to close the issue, let me know if you have other questions! Feel free to open new issues for each of the points we discussed that you’d like to work on.

Looking forward to it!

**Comment by shea256** [comment]
@vsoch Sounds good, thanks!
