### ISSUE TITLE
Method to remove all Parts from a FactoryOrder

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#93]
I'd like to be able to reset `Parts` which are directly associated with `FactoryOrders` (e.coli red20 has too many parts and bacillus subtilis essentials don't have enough, so I assume I accidentally swapped em the latter's parts to the first)

**Comment by vsoch** [comment]
Just to clarify - reset == clear the associated parts (but don't delete them)?

**Comment by Koeng101** [comment]
Yes

**Comment by vsoch** [comment]
This might take me a while to figure out, logically the admin view should expose a minus sign to remove many to many (but it doesn't) and Googling I haven't found a way yet.

**Comment by Koeng101** [comment]
Ok - I'll ignore that one for now

**Comment by vsoch** [comment]
Okay I found a way to test - adding an action to the factory order list page:

![image](https://user-images.githubusercontent.com/814322/66846841-67354300-ef40-11e9-9078-e06e05c01688.png)

**Comment by Koeng101** [comment]
Awesome!!!

**Comment by vsoch** [comment]
Okay it's live on the server!

https://github.com/vsoch/freegenes/commit/8a59d3c81da7ac382ffad229afdce055da694ed6

And actually you can already do this - I realize in retrospect that when you look at the details page for a FactoryOrder, it's not that a red minus sign is missing, but the select shows ALL the parts/plates in the database (and then you can highlight the ones wanted). For example, here we can see a subset of selected and not selected:

![image](https://user-images.githubusercontent.com/814322/66848114-7ae1a900-ef42-11e9-81d2-de03ed2b74bb.png)

(it's actually blue when the page is active)
so the staff could de-select all those selected to do the same reset action. However, it's still good that we added the button because that seems easier to do, at least to remove all globally.

**Comment by Koeng101** [comment]
Awesome! Just used it. Works!
