### ISSUE TITLE
Include Option to add your institution when creating an order.

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#97]
**Is your feature request related to a problem? Please describe.**
Currently, when a customer creates an order, there is no way to add their institution if it is not already present in the list of institutions.

**Describe the solution you'd like**
A way for a customer to add their institution to our list of institutions if it isn't already on our list.

**Describe alternatives you've considered**

Anything else?
![fg](https://user-images.githubusercontent.com/31907124/66868854-019e8200-ef53-11e9-95c1-a957bdb684fc.png)

**Comment by vsoch** [comment]
hey @hverdonk - the way they can add an institution is via their profile settings, if you scroll to the bottom -> https://freegenes.dev/u/profile. Do you want just a link to a page like that?

**Comment by hverdonk** [comment]
Sure, that would work, as long as it was something like "Don't see your institution listed? Add it here"

**Comment by vsoch** [comment]
Yep that's what I'm thinking. If it's a general form we can include it other places on the site where it might be needed.

**Comment by hverdonk** [comment]
Sounds good! Feel free to close this issue once it's in place.

**Comment by vsoch** [comment]
okay some progress - the top of the page shows a RED warning that asks them to click and add their institution, if they haven't already. We put it here because if the user adds a new institution we'd need to reload the page to see it at the bottom, and we wouldn't want them to fill it out first then get angry that the fields were lost.

![image](https://user-images.githubusercontent.com/814322/66872593-543c6600-ef74-11e9-8cc3-af1468f5376c.png)

**Comment by vsoch** [comment]
Testing a page that should be able to show the user current institutions to add (and then redirect back to checkout) OR just allow the user to click back (given that it's there)

![image](https://user-images.githubusercontent.com/814322/66873086-931eeb80-ef75-11e9-9f5a-c0c8610440e7.png)

**Comment by vsoch** [comment]
Closed with https://github.com/vsoch/freegenes/commit/06a4efca3cfc31a8bb0cf1d6faf34956dc22a97d
