### ISSUE TITLE
[MAJOR BUG] Only 1 gene is imported per plate

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#99]
**Describe the bug**
When using the official plate import system, only 1 gene is imported. All inc_xx plates after inc_9 are affected by this bug. For example, inc_11 only has BBF10K_001339. We would like for a each new well to be allocated its specific part.

In addition, for the samples that do get in (such as https://freegenes.dev/e/sample/2764762e-724d-483e-a220-29b8c111193b ), samples aren't imported properly (as referenced in #74 under "Sample import")

**To Reproduce**
- Upload csv file to FactoryOrder

**Expected behavior**
- New wells with parts specified by the CSV file

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
hey @Koeng101 - this was the section of code that I didn't understand how you wanted - please take a look at the code and make a suggestion for what needs to be fixed, or open up a PR to do so. Thank you!

**Comment by Koeng101** [comment]
Could you link me to the code section you are talking about?

**Comment by vsoch** [comment]
Sure! The import plate task is part of the factory module (e.g., fg.apps.factory) and since it's considered part of a view, and supports twist, it's under the views module folder in twist.py. The function here takes the list of rows (each a row) and the first a header, and then generates plates first, and then the rest of the logic for Part/Sample.

https://github.com/vsoch/freegenes/blob/master/fg/apps/factory/views/twist.py#L205toL390

I really struggled with this bit, if you remember from the PR that you reviewed, so your input is fairly badly needed. Thank you!

**Comment by vsoch** [comment]
okay great! Ping me if you have questions / need help.
